"""Run from backend: python -m tools.export_contract. Deterministic review fixtures."""
import json
from pathlib import Path

from app.contracts import AnalysisResponse, CategoryResult, Data, Facility, Geometry, Issue, Origin, Rules
from app.main import app
from app.rules import DistanceRule

ROOT = Path(__file__).resolve().parents[1]
EMPTY = Geometry(type="MultiPolygon", coordinates=[])
AREA = Geometry(type="Polygon", coordinates=[[
    [116.39, 39.89], [116.41, 39.89], [116.41, 39.91], [116.39, 39.91], [116.39, 39.89]
]])
ORIGIN = Origin(lng=116.4, lat=39.9)


def typescript(schema):
    def convert(node):
        if "$ref" in node:
            return node["$ref"].split("/")[-1]
        if "const" in node:
            return json.dumps(node["const"])
        if "enum" in node:
            return " | ".join(json.dumps(v) for v in node["enum"])
        if "anyOf" in node:
            return " | ".join(convert(n) for n in node["anyOf"])
        kind = node.get("type")
        if kind == "array":
            return f"Array<{convert(node.get('items', {}))}>"
        if kind == "object":
            if "properties" in node:
                return "{\n" + "\n".join(f"  {k}: {convert(v)};" for k, v in node["properties"].items()) + "\n}"
            additional = node.get("additionalProperties", {})
            return f"Record<string, {convert(additional) if isinstance(additional, dict) else 'unknown'}>"
        return {"string":"string", "integer":"number", "number":"number", "boolean":"boolean", "null":"null"}.get(kind, "unknown")
    definitions = dict(schema["$defs"], AnalysisResponse=schema)
    return "// Generated by backend/tools/export_contract.py; response defaults are always serialized.\n" + "\n\n".join(f"export type {name} = {convert(node)};" for name, node in definitions.items()) + "\n"


def export():
    (ROOT / "mocks").mkdir(exist_ok=True)
    for status in ("complete", "partial", "failed", "empty"):
        response = AnalysisResponse(
            analysis_id=f"mock-{status}-v1", generated_at="2026-09-12T00:00:00Z",
            status=status, source="mock", origin=ORIGIN,
            warnings=[Issue(code="MOCK_ONLY", message="手工构造的契约样例，所有设施和规则选择均为虚构。", scope="all")],
        )
        if status in ("complete", "empty"):
            response.rules = Rules(time_confirmation="mock_only", distance=DistanceRule(metric="walking_route", inclusive=True,
                tolerance_m=0, assessment_scope="sample", category_policy="per_category"))
            response.data = Data(geometry=AREA, uncertain_region=EMPTY, unknown_region=EMPTY,
                computation_extent=AREA, facilities=[], blind_points=[], blind_region=EMPTY,
                report="合成样例完成；评估点集为空，不能据设施零结果推导全区盲区。" if status == "empty" else "合成样例完成，起点评估三类服务均有设施。")
            for i, category in enumerate(("market", "pharmacy", "school")):
                response.data.categories[i] = CategoryResult(category=category, query_status="complete",
                    count_in_circle=0 if status == "empty" else 1,
                    service_status="unknown" if status == "empty" else "covered")
                if status == "complete":
                    response.data.facilities.append(Facility(id=f"mock-{category}", name=f"虚构{category}",
                        category=category, location=ORIGIN, in_circle=True))
            if status == "complete":
                from app.contracts import BlindPoint
                response.data.blind_points = [BlindPoint(location=ORIGIN, category=c, status="covered",
                    evidence="合成规则：该类虚构设施位于评估点，步行距离0m。") for c in ("market", "pharmacy", "school")]
        elif status == "partial":
            response.data.geometry = Geometry(type="Polygon", coordinates=[[
                [116.39,39.89], [116.4,39.89], [116.4,39.91], [116.39,39.91], [116.39,39.89]
            ]])
            response.data.uncertain_region = AREA
            response.data.unknown_region = Geometry(type="Polygon", coordinates=[[
                [116.4,39.89], [116.41,39.89], [116.41,39.91], [116.4,39.91], [116.4,39.89]
            ]])
            response.data.computation_extent = AREA
            response.data.facilities = [Facility(id="mock-pharmacy", name="虚构药店", category="pharmacy", location=ORIGIN, in_circle=True)]
            response.data.categories[1] = CategoryResult(category="pharmacy", query_status="complete", count_in_circle=1, service_status="unknown")
            response.warnings.append(Issue(code="RULES_PENDING", message="距离口径待确认，菜市场和小学数据未知。", scope="rules,categories", severity="pending"))
        else:
            response.errors = [Issue(code="UPSTREAM_UNAVAILABLE", message="合成失败样例：上游暂不可用。", scope="all", severity="error")]
        (ROOT / "mocks" / f"{status}.json").write_text(response.model_dump_json(indent=2) + "\n", encoding="utf-8")
    (ROOT / "docs" / "analysis-response.schema.json").write_text(json.dumps(AnalysisResponse.model_json_schema(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (ROOT / "docs" / "openapi.json").write_text(json.dumps(app.openapi(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (ROOT.parent / "life-circle-demo/src/api-contract.ts").write_text(typescript(AnalysisResponse.model_json_schema()), encoding="utf-8")


if __name__ == "__main__":
    export()
