// Generated by backend/tools/export_contract.py; response defaults are always serialized.
export type BlindPoint = {
  location: Origin;
  category: "market" | "pharmacy" | "school";
  status: "covered" | "blind" | "unknown";
  evidence: string;
};

export type CategoryResult = {
  category: "market" | "pharmacy" | "school";
  query_status: "complete" | "unknown" | "failed";
  count_in_circle: number | null;
  service_status: "covered" | "blind" | "unknown";
};

export type Data = {
  geometry: Geometry | null;
  uncertain_region: Geometry | null;
  unknown_region: Geometry | null;
  computation_extent: Geometry | null;
  facilities: Array<Facility> | null;
  categories: Array<CategoryResult>;
  blind_points: Array<BlindPoint> | null;
  blind_region: Geometry | null;
  report: string | null;
};

export type DistanceRule = {
  metric: "unconfirmed" | "straight_line" | "walking_route";
  threshold_m: number;
  inclusive: boolean | null;
  tolerance_m: number | null;
  assessment_scope: "unconfirmed" | "isochrone" | "community" | "sample";
  category_policy: "unconfirmed" | "per_category";
};

export type Facility = {
  id: string;
  name: string;
  category: "market" | "pharmacy" | "school";
  location: Origin;
  in_circle: boolean | null;
};

export type Geometry = {
  type: "Polygon" | "MultiPolygon";
  coordinates: Array<unknown>;
  coordinate_system: "bd09ll";
};

export type Issue = {
  code: string;
  message: string;
  scope: string;
  severity: "warning" | "error" | "pending";
};

export type Origin = {
  lng: number;
  lat: number;
};

export type Rules = {
  version: string;
  time_threshold_s: 900;
  time_inclusive: true;
  time_tolerance_s: number;
  time_confirmation: "implementation_only" | "mock_only";
  distance: DistanceRule;
};

export type AnalysisResponse = {
  schema_version: "1.0";
  analysis_id: string;
  generated_at: string;
  status: "complete" | "partial" | "failed" | "empty";
  source: "mock" | "synthetic" | "system";
  algorithm_version: string | null;
  data_updated_at: string | null;
  origin: Origin | null;
  coordinate_system: "bd09ll";
  coordinate_order: "longitude,latitude";
  units: Record<string, string>;
  rules: Rules;
  data: Data;
  algorithm: Record<string, unknown> | null;
  warnings: Array<Issue>;
  errors: Array<Issue>;
};
