// Generated by backend/tools/export_contract.py; response defaults are always serialized.
export type BlindPoint = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  major_category: "shopping" | "medical" | "education";
  minor_category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  location: Origin;
  status: "covered" | "blind" | "unknown";
  evidence: string;
};

export type CategoryResult = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  major_category: "shopping" | "medical" | "education";
  minor_category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  query_status: "complete" | "unknown" | "failed";
  count_in_circle: number | null;
  service_status: "covered" | "blind" | "unknown";
};

export type Data = {
  geometry: Geometry | null;
  uncertain_region: Geometry | null;
  unknown_region: Geometry | null;
  computation_extent: Geometry | null;
  facilities: Array<Facility> | null;
  categories: Array<CategoryResult>;
  blind_points: Array<BlindPoint> | null;
  blind_region: Geometry | null;
  report: string | null;
};

export type DistanceRule = {
  metric: "unconfirmed" | "straight_line" | "walking_route";
  threshold_m: number;
  inclusive: boolean | null;
  tolerance_m: number | null;
  assessment_scope: "unconfirmed" | "isochrone" | "community" | "sample";
  category_policy: "unconfirmed" | "per_category" | "major_minor";
};

export type Facility = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  major_category: "shopping" | "medical" | "education";
  minor_category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  id: string;
  name: string;
  location: Origin;
  in_circle: boolean | null;
};

export type Geometry = {
  type: "Polygon" | "MultiPolygon";
  coordinates: Array<unknown>;
  coordinate_system: "bd09ll";
};

export type Issue = {
  code: string;
  message: string;
  scope: string;
  severity: "warning" | "error" | "pending";
};

export type Origin = {
  lng: number;
  lat: number;
};

export type Rules = {
  version: string;
  time_threshold_s: 900;
  time_inclusive: true;
  time_tolerance_s: number;
  time_confirmation: "implementation_only" | "mock_only";
  distance: DistanceRule;
};

export type AnalysisResponse = {
  schema_version: "1.0";
  analysis_id: string;
  generated_at: string;
  status: "complete" | "partial" | "failed" | "empty";
  source: "mock" | "synthetic" | "system";
  algorithm_version: string | null;
  data_updated_at: string | null;
  origin: Origin | null;
  coordinate_system: "bd09ll";
  coordinate_order: "longitude,latitude";
  units: Record<string, string>;
  rules: Rules;
  data: Data;
  algorithm: Record<string, unknown> | null;
  warnings: Array<Issue>;
  errors: Array<Issue>;
};

export type TaskStatusResponse = {
  schema_version: "1.0";
  responseType: "task";
  taskId: string;
  status: "running" | "cancelling" | "completed" | "cancelled" | "failed";
  businessStatus: "complete" | "partial" | "failed" | "empty" | null;
  stage: string;
  requests: number;
  networkRequests: number;
  budget: 200 | 400 | 800;
  elapsedSeconds: number;
  dataSource: "synthetic" | "baidu_walking";
  error: string | null;
};

export type AssessmentPoint = {
  location: Origin;
  duration_s: number;
  categories: Array<CoverageEvidence>;
};

export type CoverageEvidence = {
  category: "shopping" | "medical" | "education";
  status: "covered" | "blind" | "unknown";
  facility_id: string | null;
  distance_m: number | null;
  reason: string;
};

export type FacilityAnalysis = {
  status: "complete" | "partial" | "failed";
  queries: Array<QueryEvidence>;
  assessments: Array<AssessmentPoint>;
  candidate_points: number;
  assessed_points: number;
  unassessed_points: number;
  network_requests: number;
  elapsed_seconds: number;
  search_radius_m: number;
  routes: Record<string, RouteEvidence>;
  serviceBlindRegions: Record<string, Geometry>;
  warnings: Array<string>;
};

export type QueryEvidence = {
  category: "market" | "supermarket" | "pharmacy" | "hospital_pharmacy" | "school";
  query: string;
  status: "complete" | "partial" | "failed" | "truncated";
  pages: number;
  returned: number;
  excluded: number;
  invalid: number;
  total: number | null;
  reason: string | null;
};

export type RouteEvidence = {
  distance_m: number | null;
  duration_s: number | null;
  endpoint_verified: boolean;
  reason: string | null;
  path: Array<Array<number>>;
};

export type TaskResultResponse = {
  schema_version: "1.0";
  responseType: "result";
  taskId: string;
  taskStatus: "completed";
  status: "complete" | "partial" | "failed" | "empty";
  businessStatus: "complete" | "partial" | "failed" | "empty";
  dataSource: "synthetic" | "baidu_walking";
  center: Origin;
  generatedAt: number;
  facilitiesStatus: "not_integrated" | "complete" | "partial" | "failed";
  facilityAnalysis: FacilityAnalysis | null;
  coordinateSystem: "bd09ll";
  coordinateOrder: "longitude,latitude";
  units: Record<string, string>;
  rules: Rules;
  data: Data;
  algorithm: Record<string, unknown> | null;
  warnings: Array<Issue>;
  errors: Array<Issue>;
  isochrone: Record<string, unknown>;
};
