import React from 'react';
import ReactDOM from 'react-dom/client';
import { ConfigProvider } from 'antd';
import zhCN from 'antd/locale/zh_CN';
import { Store } from './Store';
import App from './App';
import ApiApp from './analysis/ApiApp';
import './global.css';
const page = import.meta.env.VITE_ANALYSIS_MODE === 'demo' ? <Store><App/></Store> : <ApiApp/>;
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ConfigProvider locale={zhCN} theme={{token:{colorPrimary:'#147d70',colorInfo:'#147d70',fontFamily:'Inter, "Microsoft YaHei", "PingFang SC", sans-serif',borderRadius:7,controlHeight:36,colorText:'#233b48',fontSize:13}}}>{page}</ConfigProvider></React.StrictMode>);
